twitter:
  botUid: "USER_ID"
  consumerKey: "CONSUMER_KEY"
  consumerSecret: "CONSUMER_SECRET"
  accessToken: "ACCESS_TOKEN"
  accessTokenSecret: "ACCESS_TOKEN_SECRET"
  statusCredentials:
    auth_token: "AUTH_TOKEN"
    ct0: "CT0"
    guest_id: "GUEST_ID"
    personalization_id: "PERSONALIZATION_ID"
    twitter_sess: "TWITTER_SESS"